name: CI
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test (chunk ${{ matrix.index }})
    strategy:
      matrix:
        index: [0,1]
        total: [2]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: jest
        env:
          index: ${{matrix.index}}
          total: ${{matrix.total}}
        run: >
          npx jest --listTests
          | awk -vt=$total -vi=$index '!((NR+i)%t){print}'
          | xargs --verbose npx jest --verbose --colors --ci --bail
